CREATE TABLE USERS (
  CLERK_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  F_NAME VARCHAR(50),
  L_NAME VARCHAR(250),
  M_NAME VARCHAR(250),
  AGE BIGINT,
  BIO VARCHAR(500),
  NEW_COLUMN BIGINT -- NEW_COLUMN DOESN'T DO ANYTHING IT'S JUST AN OVERSIGHT
)

-- Seed data users
INSERT INTO
  USERS (F_NAME, L_NAME, M_NAME, AGE, BIO, NEW_COLUMN)
VALUES
  ('DAVE','WANGER','WONGER',43,'THIS WORLDS MAGIC',1)

CREATE TABLE POST (
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  SENDER BIGINT REFERENCES USERS (CLERK_ID), -- REFERENCES THE USER(ID) OF THE POSTER
  MSG VARCHAR(250), -- ATM THIS IS JUST TEXT BUT WE COULD USE THIS FOR NOW UNTIL WE MAKE A LIST OF ITEMS TABLE FOR GROCERIES
  REPLY_TO BIGINT REFERENCES POST(ID), --REFERENCES THE POST(ID) IT RESPONDS TO INSTEAD OF POST SENDER AS 1 SENDER CAN HAVE MANY POSTS
  DONE BOOLEAN
)

-- hello Seed data post
  INSERT INTO
    POST (SENDER, MSG, REPLY_TO, DONE)
  VALUES
    (1, 'I HAVE THIS JULIE', 1, TRUE)

CREATE TABLE POSTS_REACTIONS (
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  REACTION VARCHAR(1),
  USER_ID BIGINT REFERENCES USERS(CLERK_ID),
  POST_ID BIGINT REFERENCES POST(ID)
  -- COULD MAKE THE ID (USER_ID, POST_ID) IN ORDER TO FORCE THE DB TO ONLY HAVE 1 REACTION PER USER UNLESS WE WANT THE USER TO BE ABLE TO MAKE MULTIPLE REACTIONS
  -- OR DO (USER_ID, POST_ID, REACTION) TO MAKE IT SO THEY CAN STILL DO MULTIPLE REACTIONS BUT NOT OF THE SAME LETTER/EMOJI
)
  -- SEED POST_REACTIONS
(
  INSERT INTO
    POSTS_REACTIONS (REACTION, USER_ID, POST_ID)
  VALUES
    ('W', 1, 1)
    
  SELECT
    POSTER.F_NAME AS POSTER_FIRST_NAME,
    POSTER.L_NAME AS POSTER_LAST_NAME,
    POSTER.CLERK_ID AS POSTER_CLERK_ID,
    P.MSG AS POST_CONTENT,
    P.ID AS POST_ID,
    R.REACTION AS REACTION_GIVEN,
    R.ID AS REACTION_ID,
    REACTOR.F_NAME AS REACTOR_FIRST_NAME,
    REACTOR.L_NAME AS REACTOR_LAST_NAME,
    REACTOR.CLERK_ID AS REACTOR_CLERK_ID
  FROM
    POST P
    JOIN USERS POSTER ON P.SENDER = POSTER.CLERK_ID
    JOIN POSTS_REACTIONS R ON P.ID = R.POST_ID
    JOIN USERS REACTOR ON R.USER_ID = REACTOR.CLERK_ID
  ORDER BY
    P.ID;
)

---- Grocery lists

CREATE TABLE LISTS (
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  USER_ID INT REFERENCES USERS (CLERK_ID),
  LIST_NAME TEXT,
  HOUSE_SHARE BOOLEAN,
  STREET_SHARE BOOLEAN,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE LIST_ITEM (
  ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  LIST_ID REFERENCES LISTS (ID),
  ITEM_NAME TEXT,
  DONE BOOLEAN
)




